application: palsoncampus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /prefs
  script: prefs.application
  login: required

- url: /.*
  script: main.app

- url: /style
  static_dir: style

- url: /create
  script: main.create

- url: /update
  script: main.update

- url: /delete
  script: main.delete

- url: /update_profile
  script: main.update_profile

libraries:
- name: markupsafe
  version: latest
